```yaml
name: efficient-domain-tuning
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch=2.0.0
  - torchvision
  - torchaudio
  - numpy=1.24.0
  - scikit-learn=1.4.0
  - pip:
    - transformers==4.40.0
    - peft==0.10.0
    - wandb==0.16.0
    - huggingface_hub==0.22.0
    - llamafactory==0.7.0
    - evaluate==0.4.0
    - sentence-transformers==2.6.0
    - bitsandbytes>=0.39.0
    - accelerate>=0.34.0
    - datasets>=2.16.0
    - gradio>=4.0.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - pandas>=2.0.0
    - tqdm>=4.65.0
    - jupyter>=1.0.0
    - optimum>=1.15.0
```
